name: Secure CD
on:
  workflow_run:
    workflows: ["Scan Gate - Security"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with: name: build-artifact
      - name: Verify image signature
        run: cosign verify --key cosign.pub $IMAGE_URI
      - name: Terraform plan
        run: |
          cd infra
          terraform init -backend-config=backend.staging.tfvars
          terraform plan -out plan.tfplan
      - name: Conftest / OPA check on plan
        run: terraform show -json plan.tfplan > plan.json && conftest test plan.json --policy sec/policies/
      - name: Apply to staging
        run: terraform apply -auto-approve plan.tfplan
      - name: Smoke tests
        run: ./ci-scripts/smoke_tests.sh
      - name: Promote canary
        run: ./ci-scripts/promote_canary.sh
